export const statisticsCards: any = [
  [
    {
      category: "animals",
      word: "camel",
      translation: "верблюд",
      image: "images/camel.png",
      audioSrc: "audio/camel.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "animals",
      word: "crocodile",
      translation: "крокодил",
      image: "images/crocodile.png",
      audioSrc: "audio/crocodile.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "animals",
      word: "elephant",
      translation: "слон",
      image: "images/elephant.png",
      audioSrc: "audio/elephant.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "animals",
      word: "gorilla",
      translation: "горилла",
      image: "images/gorilla.png",
      audioSrc: "audio/gorilla.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "animals",
      word: "giraffe",
      translation: "жираф",
      image: "images/giraffe.png",
      audioSrc: "audio/giraffe.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "hippo",
      word: "fly",
      translation: "бегемот",
      image: "images/hippo.png",
      audioSrc: "audio/hippo.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "animals",
      word: "lion",
      translation: "лев",
      image: "images/lion.png",
      audioSrc: "audio/lion.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "animals",
      word: "parrot",
      translation: "попугай",
      image: "images/parrot.png",
      audioSrc: "audio/parrot.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "animals",
      word: "penguin",
      translation: "пингвин",
      image: "images/penguin.png",
      audioSrc: "audio/penguin.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "animals",
      word: "snake",
      translation: "змея",
      image: "images/snake.png",
      audioSrc: "audio/snake.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "animals",
      word: "tiger",
      translation: "тигр",
      image: "images/tiger.png",
      audioSrc: "audio/tiger.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "animals",
      word: "turtle",
      translation: "черепаха",
      image: "images/turtle.png",
      audioSrc: "audio/turtle.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    }
  ],
  [
    {
      category: "body",
      word: "beard",
      translation: "борода",
      image: "images/beard.jpg",
      audioSrc: "audio/beard.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "body",
      word: "back",
      translation: "спина",
      image: "images/back.jpg",
      audioSrc: "audio/back.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "body",
      word: "ear",
      translation: "ухо",
      image: "images/ear.jpg",
      audioSrc: "audio/ear.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "body",
      word: "eye",
      translation: "глаз",
      image: "images/eye.jpg",
      audioSrc: "audio/eye.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "body",
      word: "foot",
      translation: "нога",
      image: "images/foot.jpg",
      audioSrc: "audio/foot.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "body",
      word: "hand",
      translation: "рука",
      image: "images/hand.jpg",
      audioSrc: "audio/hand.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "body",
      word: "head",
      translation: "голова",
      image: "images/head.jpg",
      audioSrc: "audio/head.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "body",
      word: "lips",
      translation: "губы",
      image: "images/lips.jpg",
      audioSrc: "audio/lips.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "body",
      word: "neck",
      translation: "шея",
      image: "images/neck.jpg",
      audioSrc: "audio/neck.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "body",
      word: "nose",
      translation: "нос",
      image: "images/nose.jpg",
      audioSrc: "audio/nose.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "body",
      word: "teeth",
      translation: "зубы",
      image: "images/teeth.jpg",
      audioSrc: "audio/teeth.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "body",
      word: "tongue",
      translation: "язык",
      image: "images/tongue.jpg",
      audioSrc: "audio/tongue.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    }
  ],
  [
    {
      category: "clothes",
      word: "coat",
      translation: "пальто",
      image: "images/coat.png",
      audioSrc: "audio/coat.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "clothes",
      word: "dress",
      translation: "платье",
      image: "images/dress.png",
      audioSrc: "audio/dress.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "clothes",
      word: "jacket",
      translation: "жакет",
      image: "images/jacket.png",
      audioSrc: "audio/jacket.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "clothes",
      word: "jeans",
      translation: "джинсы",
      image: "images/jeans.png",
      audioSrc: "audio/jeans.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "clothes",
      word: "panties",
      translation: "трусы",
      image: "images/panties.png",
      audioSrc: "audio/panties.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "clothes",
      word: "shirt",
      translation: "футболка",
      image: "images/shirt.png",
      audioSrc: "audio/shirt.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "clothes",
      word: "shoes",
      translation: "обувь",
      image: "images/shoes.png",
      audioSrc: "audio/shoes.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "clothes",
      word: "shorts",
      translation: "шорты",
      image: "images/shorts.png",
      audioSrc: "audio/shorts.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "clothes",
      word: "skirt",
      translation: "юбка",
      image: "images/skirt.png",
      audioSrc: "audio/skirt.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "clothes",
      word: "socks",
      translation: "носки",
      image: "images/socks.png",
      audioSrc: "audio/socks.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "clothes",
      word: "sweater",
      translation: "свитер",
      image: "images/sweater.png",
      audioSrc: "audio/sweater.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "clothes",
      word: "swimsuit",
      translation: "купальник",
      image: "images/swimsuit.png",
      audioSrc: "audio/swimsuit.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    }
  ],
  [
    {
      category: "emotions",
      word: "angry",
      translation: "злой",
      image: "images/angry.png",
      audioSrc: "audio/angry.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "emotions",
      word: "bored",
      translation: "скучающий",
      image: "images/bored.png",
      audioSrc: "audio/bored.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "emotions",
      word: "cool",
      translation: "классный",
      image: "images/cool.png",
      audioSrc: "audio/cool.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "emotions",
      word: "crying",
      translation: "плачущий",
      image: "images/crying.png",
      audioSrc: "audio/crying.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "emotions",
      word: "excited",
      translation: "в шоке",
      image: "images/excited.png",
      audioSrc: "audio/excited.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "emotions",
      word: "greedy",
      translation: "жадный",
      image: "images/greedy.png",
      audioSrc: "audio/greedy.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "emotions",
      word: "in love",
      translation: "влюбленный",
      image: "images/in_love.png",
      audioSrc: "audio/in_love.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "emotions",
      word: "sad",
      translation: "грустный",
      image: "images/sad.png",
      audioSrc: "audio/sad.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "emotions",
      word: "scared",
      translation: "испуганный",
      image: "images/scared.png",
      audioSrc: "audio/scared.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "emotions",
      word: "screaming",
      translation: "кричащий",
      image: "images/screaming.png",
      audioSrc: "audio/screaming.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "emotions",
      word: "shocked",
      translation: "в шоке",
      image: "images/shocked.png",
      audioSrc: "audio/shocked.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "emotions",
      word: "smiling",
      translation: "улыбающийся",
      image: "images/smiling.png",
      audioSrc: "audio/smiling.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    }
  ],
  [
    {
      category: "fruits",
      word: "apple",
      translation: "яблоко",
      image: "images/apple.png",
      audioSrc: "audio/apple.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "fruits",
      word: "apricot",
      translation: "абрикос",
      image: "images/apricot.png",
      audioSrc: "audio/apricot.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "fruits",
      word: "banana",
      translation: "банан",
      image: "images/banana.png",
      audioSrc: "audio/banana.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "fruits",
      word: "blueberry",
      translation: "голубика",
      image: "images/blueberry.png",
      audioSrc: "audio/blueberry.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "fruits",
      word: "cherry",
      translation: "вишня",
      image: "images/cherry.png",
      audioSrc: "audio/cherry.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "fruits",
      word: "grapes",
      translation: "виноград",
      image: "images/grapes.png",
      audioSrc: "audio/grapes.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "fruits",
      word: "kiwi",
      translation: "киви",
      image: "images/kiwi.png",
      audioSrc: "audio/kiwi.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "fruits",
      word: "lemon",
      translation: "лимон",
      image: "images/lemon.png",
      audioSrc: "audio/lemon.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "fruits",
      word: "orange",
      translation: "апельсин",
      image: "images/orange.png",
      audioSrc: "audio/orange.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "fruits",
      word: "pear",
      translation: "груша",
      image: "images/pear.png",
      audioSrc: "audio/pear.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "fruits",
      word: "strawberry",
      translation: "клубника",
      image: "images/strawberry.png",
      audioSrc: "audio/strawberry.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "fruits",
      word: "watermelon",
      translation: "арбуз",
      image: "images/watermelon.png",
      audioSrc: "audio/watermelon.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    }
  ],
  [
    {
      category: "home stuff",
      word: "bathtub",
      translation: "ванна",
      image: "images/bathtub.png",
      audioSrc: "audio/bathtub.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "home stuff",
      word: "bed",
      translation: "кровать",
      image: "images/bed.png",
      audioSrc: "audio/bed.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "home stuff",
      word: "chair",
      translation: "стул",
      image: "images/chair.png",
      audioSrc: "audio/chair.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "home stuff",
      word: "fridge",
      translation: "холодильник",
      image: "images/fridge.png",
      audioSrc: "audio/fridge.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "home stuff",
      word: "microwave",
      translation: "микроволновка",
      image: "images/microwave.png",
      audioSrc: "audio/microwave.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "home stuff",
      word: "mirror",
      translation: "зеркало",
      image: "images/mirror.png",
      audioSrc: "audio/mirror.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "home stuff",
      word: "sink",
      translation: "раковина",
      image: "images/sink.png",
      audioSrc: "audio/sink.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "home stuff",
      word: "sofa",
      translation: "диван",
      image: "images/sofa.png",
      audioSrc: "audio/sofa.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "home stuff",
      word: "table",
      translation: "стол",
      image: "images/table.png",
      audioSrc: "audio/table.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "home stuff",
      word: "toilet",
      translation: "унитаз",
      image: "images/toilet.png",
      audioSrc: "audio/toilet.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "home stuff",
      word: "TV",
      translation: "телевизор",
      image: "images/tv.png",
      audioSrc: "audio/tv.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "home stuff",
      word: "wardrobe",
      translation: "шкаф",
      image: "images/wardrobe.png",
      audioSrc: "audio/wardrobe.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    }
  ],
  [
    {
      category: "nature",
      word: "cloud",
      translation: "облако",
      image: "images/cloud.png",
      audioSrc: "audio/cloud.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "nature",
      word: "desert",
      translation: "пустыня",
      image: "images/desert.png",
      audioSrc: "audio/desert.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "nature",
      word: "forest",
      translation: "лес",
      image: "images/forest.png",
      audioSrc: "audio/forest.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "nature",
      word: "lake",
      translation: "озеро",
      image: "images/lake.png",
      audioSrc: "audio/lake.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "nature",
      word: "moon",
      translation: "луна",
      image: "images/moon.png",
      audioSrc: "audio/moon.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "nature",
      word: "mountain",
      translation: "гора",
      image: "images/mountain.png",
      audioSrc: "audio/mountain.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "nature",
      word: "river",
      translation: "река",
      image: "images/river.png",
      audioSrc: "audio/river.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "nature",
      word: "sea",
      translation: "море",
      image: "images/sea.png",
      audioSrc: "audio/sea.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "nature",
      word: "sun",
      translation: "солнце",
      image: "images/sun.png",
      audioSrc: "audio/sun.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "nature",
      word: "water",
      translation: "вода",
      image: "images/water.png",
      audioSrc: "audio/water.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "nature",
      word: "waterfall",
      translation: "водопад",
      image: "images/waterfall.png",
      audioSrc: "audio/waterfall.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "nature",
      word: "wind",
      translation: "ветер",
      image: "images/wind.png",
      audioSrc: "audio/wind.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    }
  ],
  [
    {
      category: "vegetables",
      word: "beet",
      translation: "свекла",
      image: "images/beet.png",
      audioSrc: "audio/beet.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "vegetables",
      word: "cabbage",
      translation: "капуста",
      image: "images/cabbage.png",
      audioSrc: "audio/cabbage.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "vegetables",
      word: "carrot",
      translation: "морковь",
      image: "images/carrot.png",
      audioSrc: "audio/carrot.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "vegetables",
      word: "corn",
      translation: "кукуруза",
      image: "images/corn.png",
      audioSrc: "audio/corn.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "vegetables",
      word: "cucumber",
      translation: "огурец",
      image: "images/cucumber.png",
      audioSrc: "audio/cucumber.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "vegetables",
      word: "garlic",
      translation: "чеснок",
      image: "images/garlic.png",
      audioSrc: "audio/garlic.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "vegetables",
      word: "mushroom",
      translation: "гриб",
      image: "images/mushroom.png",
      audioSrc: "audio/mushroom.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "vegetables",
      word: "onion",
      translation: "лук",
      image: "images/onion.png",
      audioSrc: "audio/onion.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "vegetables",
      word: "peas",
      translation: "горох",
      image: "images/peas.png",
      audioSrc: "audio/peas.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "vegetables",
      word: "pepper",
      translation: "перец",
      image: "images/pepper.png",
      audioSrc: "audio/pepper.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "vegetables",
      word: "potato",
      translation: "картошка",
      image: "images/potato.png",
      audioSrc: "audio/potato.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    },
    {
      category: "vegetables",
      word: "tomato",
      translation: "помидор",
      image: "images/tomato.png",
      audioSrc: "audio/tomato.mp3",
      trainMode: 0,
      correct: 0,
      errors: 0,
      errorsPercent: 0
    }
  ]
];
